### ISSUE TITLE
Release a new version of s3-loader

### ISSUE THREAD

**Issue by arihantsurana** [snowplow/snowplow-s3-loader#136]
Some of the interesting changes I am looking forward to using, are in the develop branch. Including but not limited to the ability to deposit data on s3 in time-based subdirectories.
It has been 10 months since the last release of the s3 loader. 
Please release a new version of s3 loader

**Comment by BenFradet** [comment]
hey @arihantsurana , when you want a release done feel free to open a PR like #138 and we'll gladly publish an rc :+1:
