### ISSUE TITLE
Upgrade scala to newer versions

### ISSUE THREAD

**Issue by jaysonsantos** [snowplow/snowplow-s3-loader#160]
Hey there, I would like to send a PR to support kafka and it uses java's futures and I saw that newer scala versions can convert these futures into scala ones to be able to use things like `onComplete`.
The question is, is it ok if I send a PR to try and upgrade scala to the newest version possible?
Also, is kafka something of your interest?

**Comment by chuwy** [comment]
Hey @jaysonsantos, sorry we missed your question. Technically, answers to both your questions are "yes", but we're planning a big refactoring soon, so I'm not sure if it worth your efforts as the Loader will be significantly overhauled anyway.

**Comment by benjben** [comment]
Handled by #182
