### ISSUE TITLE
Add sink timestamp section into file names

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow-s3-loader#173]
Currently file names are generated here: https://github.com/snowplow/snowplow-s3-loader/blob/master/src/main/scala/com.snowplowanalytics.s3/loader/KinesisS3Emitter.scala#L150 with only year/month/day and Kinesis sequence number, which are mostly useless if we want to reply some set of data from S3.

/cc @istreeter

**Comment by colmsnowplow** [comment]
There is another purpose to this requirement, and an important one. [If the path doesn't follow a particular convention](https://stackoverflow.com/questions/42527438/aws-athena-use-folder-name-as-partition), then it is not possible to partition the data and limit queries via Athena. 

Ideally the S3 loader will be able to create files in a manner which allows one to easily create partitioned athena tables, and only load certain partitions. (the old format `run=` convention served this purpose well).

**Comment by benjben** [comment]
We could also use [this parameter](https://github.com/snowplow/snowplow-s3-loader/blob/0.7.0/examples/config.hocon.sample#L94) to partition data by date.

**Comment by benjben** [comment]
`2020-12-22-49613548169053493378838656625866917741098839399456571394-49613548169053493378838657029012246511267725570343960578.gz` becomes `2020-12-22-125000-49613548169053493378838656625866917741098839399456571394-49613548169053493378838657029012246511267725570343960578.gz`
