### ISSUE TITLE
Prevent empty files from being written

### ISSUE THREAD

**Issue by colmsnowplow** [snowplow/snowplow-s3-loader#178]
The s3 loader can sometimes write empty files. My guess is this happens when there is no data for the cadence it's configured to.

It would be nice to prevent this and simply do nothing if there's no data to write.

**Comment by jbeemster** [comment]
My experience here is that it never writes empty files (0.6.0 version at least) - is this something that has changed with 0.7.0?

**Comment by colmsnowplow** [comment]
Ah! I confused myself [when I saw this discourse post](https://discourse.snowplowanalytics.com/t/shredded-bad-bucket-contains-zero-byte-files/4040).

I mistook him to mean that the bad bucket had empty files - but actually this is a known issue further downstream, I think it's to do with s3DistCP. Closing!
