### ISSUE TITLE
Migrate from Travis to GH actions

### ISSUE THREAD

**Issue by benjben** [snowplow/snowplow-s3-loader#181]
@chuwy could you add `SNYK_TOKEN` and [these env variables](https://github.com/snowplow/snowplow-s3-loader/blob/master/.travis.yml#L25-L30) please?

**Comment by chuwy** [comment]
Hey @benjben! Added these:


* `BINTRAY_SNOWPLOW_GENERIC_API_KEY`
* `BINTRAY_SNOWPLOW_GENERIC_USER`
* `DOCKER_PASSWORD`
* `DOCKER_USERNAME`
* `SNYK_TOKEN`

But I actually don't think we should be adding bintray (unless I'm missing something and it's required somewhere)

**Comment by benjben** [comment]
Great thanks ! Indeed I don't see a reason why adding Bintray either, it was probably used back in the time where the jar was uploaded. The latest 3 are enough
