### ISSUE TITLE
S3-Loader-Kiesis seems to handle the aws-access-chain differently than other snowplow projects

### ISSUE THREAD

**Issue by jgrebe** [snowplow/snowplow-s3-loader#257]
Hey, currently I'm trying to use the snowplow stack in Kubernetes. 

The access management for my AWS resources is controlled via service accounts given directly to the pods in their helm release.
While the kinesis-collector/enrichment pod are working just fine with kinesis and log export etc. the loader pod immediately fails on startup since he tries to use the cluster default service-account even though an own one is provided in the same way as for the collector or the enricher.

Since I can't figure out any mistakes in the provided access chain on our side, I thought the loader might handle the default access chain in another way that the enricher/collector handle it. But maybe you have an idea what differs the loader from the other project in terms of aws-access handling.

**Comment by benjben** [comment]
Hi @jgrebe , we've just released S3 loader `2.2.5`. It comes with STS, which should make it possible for you to authenticate on EKS
