### ISSUE TITLE
Add support for server-side encryption

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-s3-loader#53]
http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingServerSideEncryption.html

**Comment by alexanderdean** [comment]
This is top priority.

**Comment by BenFradet** [comment]
the s3 loader can write to SSE-S3 encrypted bucket out of the box, closing

**Comment by alexanderdean** [comment]
De-scheduling
